# Generated by Django 6.0.4 on 2026-04-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rifle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('caliber', models.CharField(max_length=50)),
                ('weight_lbs', models.FloatField()),
            ],
        ),
    ]
